do $$ begin create type "ProductType" as enum ('DIGITAL','PHYSICAL','SUBSCRIPTION','BUNDLE'); exception when duplicate_object then null; end $$;
do $$ begin create type "ProductStatus" as enum ('ACTIVE','INACTIVE','ARCHIVED'); exception when duplicate_object then null; end $$;
do $$ begin create type "PaymentStatus" as enum ('PENDING','PAID','FAILED','REFUNDED','PARTIALLY_REFUNDED'); exception when duplicate_object then null; end $$;
do $$ begin create type "FulfillmentStatus" as enum ('NOT_STARTED','PROCESSING','AWAITING_FULFILLMENT','PICKING','PACKED','SHIPPED','DELIVERED','COMPLETED','ISSUE_EXCEPTION'); exception when duplicate_object then null; end $$;
do $$ begin create type "OrderType" as enum ('DIGITAL','PHYSICAL','SUBSCRIPTION','MIXED'); exception when duplicate_object then null; end $$;
do $$ begin create type "SubscriptionStatus" as enum ('ACTIVE','PAUSED','CANCELLED','PAST_DUE','INCOMPLETE'); exception when duplicate_object then null; end $$;
do $$ begin create type "DigitalAccessStatus" as enum ('ACTIVE','EXPIRED','REVOKED'); exception when duplicate_object then null; end $$;
do $$ begin create type "FulfillmentTaskStatus" as enum ('PENDING','AWAITING_FULFILLMENT','PICKING','PACKED','READY_TO_SHIP','SHIPPED','DELIVERED','ISSUE_EXCEPTION'); exception when duplicate_object then null; end $$;
do $$ begin create type "Priority" as enum ('LOW','NORMAL','HIGH','URGENT'); exception when duplicate_object then null; end $$;
do $$ begin create type "InventoryMovementType" as enum ('SALE','RESERVE','RELEASE','RESTOCK','ADJUSTMENT','REFUND_RETURN'); exception when duplicate_object then null; end $$;
do $$ begin create type "StaffRole" as enum ('ADMIN','OPERATIONS','FULFILLMENT','SUPPORT','FINANCE'); exception when duplicate_object then null; end $$;
do $$ begin create type "IssueType" as enum ('REFUND_REQUEST','DAMAGED_ITEM','MISSING_ITEM','DELIVERY_ISSUE','DIGITAL_ACCESS_ISSUE','OTHER'); exception when duplicate_object then null; end $$;
do $$ begin create type "SupportIssueStatus" as enum ('OPEN','IN_REVIEW','WAITING_CUSTOMER','RESOLVED','REJECTED'); exception when duplicate_object then null; end $$;
do $$ begin create type "NotificationSeverity" as enum ('INFO','WARNING','CRITICAL'); exception when duplicate_object then null; end $$;

alter table products add column if not exists name text;
alter table products add column if not exists product_type "ProductType" not null default 'DIGITAL';
alter table products add column if not exists sku text unique;
alter table products add column if not exists category text;
alter table products add column if not exists price integer;
alter table products add column if not exists currency text not null default 'AUD';
alter table products add column if not exists stripe_product_id text;
alter table products add column if not exists is_subscription boolean not null default false;
alter table products add column if not exists billing_interval text;
alter table products add column if not exists stock_quantity integer not null default 0;
alter table products add column if not exists reserved_stock_quantity integer not null default 0;
alter table products add column if not exists low_stock_threshold integer not null default 0;
alter table products add column if not exists digital_file_id text;
alter table products add column if not exists secure_asset text;
alter table products add column if not exists fulfillment_instructions text;

alter table orders add column if not exists order_number text unique;
alter table orders add column if not exists customer_id text;
alter table orders add column if not exists stripe_customer_id text;
alter table orders add column if not exists stripe_checkout_session_id text unique;
alter table orders add column if not exists stripe_payment_intent_id text;
alter table orders add column if not exists stripe_subscription_id text;
alter table orders add column if not exists total_amount integer not null default 0;
alter table orders add column if not exists currency text not null default 'AUD';
alter table orders add column if not exists payment_status "PaymentStatus" not null default 'PENDING';
alter table orders add column if not exists fulfillment_status "FulfillmentStatus" not null default 'NOT_STARTED';
alter table orders add column if not exists order_type "OrderType" not null default 'DIGITAL';
alter table orders add column if not exists customer_email text;
alter table orders add column if not exists shipping_address jsonb;
alter table orders add column if not exists billing_address jsonb;
alter table orders add column if not exists updated_at timestamptz not null default now();

create table if not exists order_items (id text primary key, order_id text not null references orders(id), product_id text not null references products(id), product_name_snapshot text not null, sku_snapshot text, quantity integer not null default 1, unit_price integer not null, total_price integer not null, product_type "ProductType" not null, fulfillment_required boolean not null default false, digital_access_granted boolean not null default false, created_at timestamptz not null default now());
create table if not exists ecommerce_subscriptions (id text primary key, customer_id text, user_id text references users(id), stripe_subscription_id text unique not null, stripe_customer_id text, product_id text references products(id), tier text, status "SubscriptionStatus" not null default 'INCOMPLETE', current_period_start timestamptz, current_period_end timestamptz, renewal_date timestamptz, cancel_at_period_end boolean not null default false, cancelled_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists digital_access (id text primary key, customer_id text, product_id text not null references products(id), order_id text references orders(id), subscription_id text references ecommerce_subscriptions(id), access_status "DigitalAccessStatus" not null default 'ACTIVE', access_starts_at timestamptz not null default now(), access_ends_at timestamptz, download_count integer not null default 0, last_downloaded_at timestamptz, created_at timestamptz not null default now());
create table if not exists fulfillment_tasks (id text primary key, order_id text not null references orders(id), assigned_to_staff_id text, status "FulfillmentTaskStatus" not null default 'PENDING', priority "Priority" not null default 'NORMAL', due_date timestamptz, packing_notes text, internal_notes text, packed_at timestamptz, shipped_at timestamptz, delivered_at timestamptz, tracking_number text, courier text, shipping_label_url text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists inventory_movements (id text primary key, product_id text not null references products(id), movement_type "InventoryMovementType" not null, quantity_change integer not null, previous_stock integer not null, new_stock integer not null, reason text not null, order_id text references orders(id), staff_id text, created_at timestamptz not null default now());
create table if not exists bundle_components (id text primary key, bundle_product_id text not null references products(id), component_product_id text not null references products(id), quantity integer not null default 1, component_type "ProductType" not null, fulfillment_instructions text, created_at timestamptz not null default now());
create table if not exists staff_members (id text primary key, user_id text, email text unique not null, name text, role "StaffRole" not null, active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists activity_logs (id text primary key, actor_id text, actor_role text, entity_type text not null, entity_id text not null, action text not null, previous_value jsonb, new_value jsonb, ip_address text, user_agent text, created_at timestamptz not null default now());
create table if not exists support_issues (id text primary key, customer_id text, order_id text references orders(id), issue_type "IssueType" not null, status "SupportIssueStatus" not null default 'OPEN', priority "Priority" not null default 'NORMAL', notes text, resolution text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists notifications (id text primary key, type text not null, title text not null, message text not null, severity "NotificationSeverity" not null default 'INFO', related_entity_type text, related_entity_id text, read_at timestamptz, created_at timestamptz not null default now());
