import Link from "next/link";
import FanXCheckoutButton from "@/components/FanXCheckoutButton";
import { getFanXDb } from "@/lib/fanx-db";

export const dynamic = "force-dynamic";

export default async function TiersPage(){
  const db=getFanXDb();
  const {data:creator}=await db.from("fanx_creators").select("id,display_name,slug").eq("slug","scarlett-may").single();
  const {data:tiers}=creator?await db.from("fanx_tiers").select("id,name,description,price_cents,billing_interval,perks,sort_order").eq("creator_id",creator.id).eq("active",true).order("sort_order"): {data:[]};
  return <main style={main}><header style={header}><Link href="/fanxfantasy"><img src="/fanx/logo.png" alt="FanXFantasy" style={{height:54,width:170,objectFit:"contain"}}/></Link><div><Link href="/fanxfantasy/explore" style={nav}>Explore</Link><Link href="/fanxfantasy/auth" style={nav}>Account</Link></div></header><section style={wrap}><span style={kicker}>Choose your experience</span><h1 style={h1}>Subscribe to {creator?.display_name||"Scarlett May"}</h1><p style={muted}>Recurring access is billed securely through Stripe. Cancel at any time; access follows the billing state recorded by the webhook.</p><div style={grid}>{(tiers||[]).map((tier,index)=><article key={tier.id} style={{...card,borderColor:index===1?"#ff2d8d":"#2b2b33",boxShadow:index===1?"0 0 34px rgba(255,45,141,.12)":"none"}}><div style={kicker}>{index===1?"Most popular":"Membership"}</div><h2>{tier.name}</h2><div style={{fontSize:34,fontWeight:900}}>${(tier.price_cents/100).toFixed(2)}<small style={{fontSize:14,color:"#999"}}>/{tier.billing_interval}</small></div><p style={muted}>{tier.description}</p><ul style={{color:"#c5c5cf",lineHeight:1.9,paddingLeft:20}}>{Array.isArray(tier.perks)?tier.perks.map((p)=><li key={String(p)}>{String(p)}</li>):null}</ul><FanXCheckoutButton kind="subscription" creatorSlug="scarlett-may" itemKey={tier.name} className="fanx-checkout">Subscribe</FanXCheckoutButton></article>)}</div><div style={note}><b>18+ verified access</b><span>Payment does not bypass age assurance. Mature content remains protected server-side.</span></div></section></main>
}
const main:React.CSSProperties={minHeight:"100vh",background:"#070708",color:"#fff",fontFamily:"Inter,system-ui,sans-serif"};const header:React.CSSProperties={display:"flex",justifyContent:"space-between",alignItems:"center",padding:"12px clamp(16px,4vw,54px)",borderBottom:"1px solid #25252b"};const wrap:React.CSSProperties={width:"min(1100px,92vw)",margin:"0 auto",padding:"60px 0 100px"};const kicker:React.CSSProperties={color:"#ff2d8d",fontSize:12,fontWeight:900,textTransform:"uppercase",letterSpacing:".13em"};const h1:React.CSSProperties={fontSize:"clamp(2.2rem,6vw,4.6rem)",margin:"10px 0"};const muted:React.CSSProperties={color:"#aaaab5",lineHeight:1.65};const grid:React.CSSProperties={display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(240px,1fr))",gap:16,marginTop:30};const card:React.CSSProperties={border:"1px solid #2b2b33",borderRadius:20,padding:22,background:"#111115"};const note:React.CSSProperties={display:"flex",gap:12,marginTop:24,padding:15,border:"1px solid #3b2a31",borderRadius:14,color:"#cbbac2"};const nav:React.CSSProperties={color:"#ccc",marginLeft:16};
