import Image from "next/image";
import Link from "next/link";

const tiles = [["01", "Sell", "Services, products, memberships and bookings in one polished digital storefront."], ["02", "Manage", "A private workspace for offers, customers, payments and the tasks that need approval."], ["03", "Grow", "Optional AI workers help with follow-up, content and operations while you stay in control."]];
const capabilities = [["Marketplace", "Be discoverable", "A public, searchable place for customers to find your business."], ["Your machine", "Make buying simple", "Present offers clearly, capture leads and accept bookings or payments."], ["AI workforce", "Keep work moving", "Add practical, permissioned assistance when your operation needs it."]];

export default function HomePage() {
  return <main className="cqa-home">
    <section className="cqa-home-hero"><div className="cqa-home-shell cqa-home-grid">
      <div className="cqa-home-copy"><p className="cqa-kicker"><i /> CREATIVE QUALITY AUSTRALIA · DIGITAL BUSINESS SYSTEMS</p><h1>Turn your business into a <span>digital vending machine.</span></h1><p className="cqa-home-lede">Give customers one clear place to discover, buy, book and return — with a private owner workspace and optional AI help behind the scenes.</p><div className="cqa-home-actions"><Link href="/onboarding" className="button primary">Launch my machine <b>→</b></Link><Link href="/marketplace" className="button ghost">Explore marketplace</Link></div><div className="cqa-home-signals"><span><b>24/7</b> your storefront</span><span><b>ONE</b> owner workspace</span><span><b>YOU</b> approve changes</span></div></div>
      <div className="cqa-command-tile"><div className="cqa-tile-top"><span><i /> CQA / BUSINESS MACHINE</span><b>READY</b></div><Image src="/images/scarlett-may-activewear.png" alt="Scarlett May activewear collection" width={348} height={653} priority className="cqa-scarlett-image"/><div className="cqa-tile-screen"><small>YOUR DIGITAL FRONT DOOR</small><strong>Everything your customers need, in one place.</strong><span>DISCOVER · BUY · BOOK · RETURN</span></div><div className="cqa-tile-slots"><div><small>01</small><b>Offers</b><span>Products & services</span></div><div><small>02</small><b>Bookings</b><span>Simple scheduling</span></div><div><small>03</small><b>AI support</b><span>Owner-approved work</span></div></div><div className="cqa-tile-console"><span><i /> SYSTEM ONLINE</span><Link href="/onboarding">OPEN WORKSPACE →</Link></div></div>
    </div></section>
    <section className="cqa-home-shell cqa-home-section"><header className="cqa-section-head"><div><p className="cqa-kicker"><i /> A SIMPLE CUSTOMER PATH</p><h2>A site that works like a <span>well-run business.</span></h2></div><p>No cobbled-together tools. Build a clear customer experience, then manage it from one private control room.</p></header><div className="cqa-float-grid">{tiles.map(([n, t, c]) => <article className="cqa-float-tile" key={t}><span>{n}</span><h3>{t}</h3><p>{c}</p><i>↗</i></article>)}</div></section>
    <section className="cqa-home-band"><div className="cqa-home-shell cqa-capability-grid">{capabilities.map(([l, t, c], i) => <article className="cqa-capability-tile" key={l}><span>0{i + 1} / {l.toUpperCase()}</span><h3>{t}</h3><p>{c}</p><Link href={i === 0 ? "/marketplace" : i === 1 ? "/onboarding" : "/workers"}>Learn more →</Link></article>)}</div></section>
    <section className="cqa-home-shell cqa-home-section cqa-owner-section"><div><p className="cqa-kicker"><i /> BUILT FOR BUSINESS OWNERS</p><h2>Keep the control. <span>Lose the technical maze.</span></h2><p>Start with your business, your offers and your customers. CQA provides the storefront, structure and optional workforce — not a generic template you have to assemble alone.</p><Link href="/pricing" className="button primary">View machine plans <b>→</b></Link></div><aside className="cqa-owner-tile"><small>OWNER CONTROL PANEL</small><strong>One workspace.<br />A clearer business.</strong><div><span>Offers <b>04 live</b></span><span>Customer requests <b>12 new</b></span><span>AI tasks <b>03 awaiting approval</b></span></div></aside></section>
    <section className="cqa-home-shell cqa-final-tile"><div><p className="cqa-kicker"><i /> READY WHEN YOU ARE</p><h2>Build a business machine your customers will actually use.</h2></div><Link href="/onboarding" className="button primary">Start guided setup <b>→</b></Link></section>
  </main>;
}
