import Link from "next/link";

const workers = [
  ["Content Worker", "Create consistent, on-brand content faster.", "Creators and personal brands", "15 minutes", "pink"],
  ["Lead Generation Worker", "Turn more visitors into qualified conversations.", "Service businesses and agencies", "20 minutes", "cyan"],
  ["Sales Worker", "Follow up, qualify prospects, and help convert demand around the clock.", "Digital products and online offers", "20 minutes", "gold"]
] as const;

export default function HomePage() {
  return <main className="home-page">
    <section className="hero-shell cqa-neon-hero"><div className="hero-orb hero-orb-one" /><div className="hero-orb hero-orb-two" /><div className="container hero-grid cqa-hero-grid"><div className="hero-copy"><span className="eyebrow">Turn traffic into revenue with deployable AI Workers.</span><h1>Deploy Revenue-Ready <span>AI Workers in Minutes</span></h1><p className="hero-lead">Launch plug-and-play AI machines for content, lead generation, and sales—built for creators and digital businesses that want faster growth.</p><div className="hero-actions"><Link href="/onboarding" className="button primary">Launch My AI Machine</Link><Link href="/marketplace" className="button ghost">View Marketplace</Link></div><div className="hero-signal-row"><span>BUILT FOR CREATOR BRANDS</span><i /><span>FAST SETUP</span><i /><span>SCALABLE AUTOMATIONS</span></div></div><aside className="worker-hero-panel"><span className="eyebrow">AI WORKFORCE</span><strong>01 / 03</strong><h2>Content. Leads. Sales.</h2><p>Deploy the repeatable work that creates momentum, then scale your workforce as you grow.</p><div><span>CONTENT</span><span>LEADS</span><span>SALES</span></div></aside></div></section>
    <section className="container section-block"><div className="section-heading"><div><span className="eyebrow">Choose Your AI Worker</span><h2>Prebuilt systems designed to create content, capture leads, and convert sales—without hiring a full team.</h2></div></div><div className="worker-grid">{workers.map(([title, description, bestFor, setup, accent]) => <article className={`worker-card ${accent}`} key={title}><span className="worker-index">AI WORKER</span><h3>{title}</h3><p>{description}</p><dl><div><dt>Best for</dt><dd>{bestFor}</dd></div><div><dt>Setup</dt><dd>{setup}</dd></div></dl><Link href="/onboarding" className="card-link">Deploy Worker →</Link></article>)}</div></section>
    <section className="dark-band"><div className="container section-block"><div className="section-heading compact"><div><span className="eyebrow">Built to produce outcomes</span><h2>Your AI Workers are designed around the jobs that move revenue—not vague automation for its own sake.</h2></div></div><div className="outcome-grid">{["Create more content", "Capture more qualified leads", "Follow up faster", "Convert more sales", "Scale without adding headcount"].map((outcome, index) => <div key={outcome}><span>0{index + 1}</span><strong>{outcome}</strong></div>)}</div></div></section>
    <section className="container section-block"><div className="section-heading"><div><span className="eyebrow">How it works</span><h2>From outcome to operating system in minutes.</h2></div></div><div className="flow-grid worker-flow-grid"><article className="flow-card"><span>01</span><h3>Choose your Worker</h3><p>Pick the revenue outcome you want to improve.</p></article><article className="flow-card"><span>02</span><h3>Connect your tools</h3><p>Link your brand, offer, and existing workflow.</p></article><article className="flow-card"><span>03</span><h3>Deploy and grow</h3><p>Your AI Worker begins handling repeatable work in minutes.</p></article></div></section>
    <section className="container final-panel"><div><span className="eyebrow">READY TO DEPLOY?</span><h2>Your next growth hire does not need another seat at the table.</h2><p>Launch your first AI Machine today.</p></div><Link href="/onboarding" className="button primary">Launch My AI Machine</Link></section>
  </main>;
}
