import Link from "next/link";
import styles from "./FanXFantasyApp.module.css";

type View = "home"|"explore"|"profile"|"feed"|"unlock"|"tiers"|"messages"|"marketplace"|"checkout"|"success"|"library"|"dashboard"|"character-studio"|"create"|"analytics";

const nav: Array<[View,string,string]> = [
  ["home","Home","⌂"],["explore","Explore","⌕"],["feed","Feed","▣"],["messages","Messages","✉"],["library","Library","▤"],
  ["marketplace","Marketplace","◆"],["dashboard","Creator Dashboard","▦"],["character-studio","AI Character Studio","✦"],["create","Create Content","＋"],["analytics","Analytics","↗"],
];
const creators = [
  ["Scarlett May","@scarlettmay","4.9","pink"],["Luna Everly","@lunaeverly","4.8","alt"],["Aria Monroe","@ariamonroe","4.7","blue"],["Violet Rain","@violetrain","4.9","alt"],
];
const href=(v:View)=>v==="home"?"/fanxfantasy":`/fanxfantasy/${v}`;

function Header(){return <><header className={styles.topbar}><Link className={styles.brand} href="/fanxfantasy">Fan<b>X</b>Fantasy</Link><div className={styles.topActions}><Link className={styles.ghost} href="/fanxfantasy/explore">Explore</Link><Link className={styles.primary} href="/fanxfantasy/tiers">Join Now</Link></div></header></>}
function Shell({view,children}:{view:View;children:React.ReactNode}){return <main className={styles.shell}><Header/><div className={styles.layout}><aside className={styles.sidebar}>{nav.map(([v,label,icon])=><Link key={v} className={`${styles.sideLink} ${view===v?styles.active:""}`} href={href(v)}><span>{icon}</span>{label}</Link>)}<div className={styles.ageNote}><b>18+</b><span>Adults-only content areas require age confirmation.</span></div></aside><section className={styles.content}>{children}</section></div><nav className={styles.bottomNav}>{nav.slice(0,5).map(([v,label,icon])=><Link href={href(v)} key={v}><b>{icon}</b>{label}</Link>)}</nav></main>}
function CreatorCards(){return <div className={styles.grid4}>{creators.map(([name,handle,rating,tone],i)=><Link href="/fanxfantasy/profile" className={styles.card} key={name}><div className={`${styles.creatorThumb} ${tone==="alt"?styles.alt:tone==="blue"?styles.blue:""}`}></div><div className={styles.creatorMeta}><div><h3>{name} {i===0?"✓":""}</h3><span className={styles.muted}>{handle}</span></div><span className={styles.tag}>★ {rating}</span></div></Link>)}</div>}

function Home(){return <><section className={styles.hero}><div><span className={styles.kicker}>AI creators · real fantasies · premium access</span><h1>Live your <span>fantasy.</span></h1><p>Discover AI creator worlds, unlock premium drops, subscribe to exclusive tiers, message creators and build your own AI persona from one premium marketplace.</p><div className={styles.actions}><Link className={styles.primary} href="/fanxfantasy/explore">Explore creators</Link><Link className={styles.ghost} href="/fanxfantasy/dashboard">Join as creator</Link></div><div className={styles.ageNote}><b>18+</b><span>FanXFantasy is an adults-only platform. Age confirmation is required before accessing mature areas.</span></div></div><div className={styles.heroCard}/></section><div className={styles.sectionHead}><div><span className={styles.kicker}>Trending now</span><h2>Featured creators</h2></div><Link className={styles.muted} href="/fanxfantasy/explore">View all →</Link></div><CreatorCards/><div className={styles.sectionHead}><div><span className={styles.kicker}>Featured drop</span><h2>Scarlett May — Neon After Dark</h2></div></div><div className={styles.grid3}><div className={styles.product}><div className={styles.productMedia}/><div className={styles.productCopy}><b>Premium Image Bundle</b><p className={styles.muted}>20 cinematic creator images</p><span className={styles.price}>$24.99 AUD</span></div></div><div className={styles.product}><div className={styles.productMedia}/><div className={styles.productCopy}><b>Late Night Video Pack</b><p className={styles.muted}>Short-form premium clips</p><span className={styles.price}>$39.99 AUD</span></div></div><div className={styles.product}><div className={styles.productMedia}/><div className={styles.productCopy}><b>Scarlett Prompt Vault</b><p className={styles.muted}>Character-consistent prompt system</p><span className={styles.price}>$19.99 AUD</span></div></div></div></>}
function Explore(){return <><div className={styles.sectionHead}><div><span className={styles.kicker}>Explore creators</span><h2>Find your next obsession</h2></div></div><div className={styles.tabs}>{["All","Trending","New","Popular","SFW","18+"].map((x,i)=><span key={x} className={`${styles.tab} ${i===1?styles.tabActive:""}`}>{x}</span>)}</div><CreatorCards/><div className={styles.sectionHead}><h2>More creators</h2></div><CreatorCards/></>}
function Profile(){return <><section className={styles.profileHero}><div className={styles.cover}/><div className={styles.profileInfo}><div className={styles.avatar}/><h1>Scarlett May ✓</h1><p className={styles.muted}>@scarlettmay · 18.7K followers · 4.9 rating</p><p>Your fantasy, my world. Exclusive cinematic drops, private chat, premium image sets and VIP requests.</p><div className={styles.actions}><button className={styles.ghost}>Follow</button><Link className={styles.primary} href="/fanxfantasy/tiers">Subscribe</Link></div></div></section><div className={styles.tabs}><span className={`${styles.tab} ${styles.tabActive}`}>Posts</span><span className={styles.tab}>Bundles</span><span className={styles.tab}>Products</span><span className={styles.tab}>About</span></div><div className={styles.grid3}>{[1,2,3,4,5,6].map(n=><Link href="/fanxfantasy/unlock" className={styles.card} key={n}><div className={`${styles.media} ${n>2?styles.locked:""}`}/><div className={styles.creatorMeta}><b>{n%2?"Neon nights":"Private collection"}</b><span className={styles.price}>{n>2?"$8.99":"VIP"}</span></div></Link>)}</div></>}
function Feed(){return <div className={styles.feed}><div>{[1,2].map((n)=><article className={styles.post} key={n}><div className={styles.postHead}><b>{n===1?"Scarlett May ✓":"Luna Everly ✓"}</b><span className={styles.muted}>2m</span></div><div className={`${styles.postMedia} ${n===1?styles.locked:""}`}/><div className={styles.postFoot}><b>♥ 1.2K &nbsp; ◯ 128</b><p>{n===1?"A little late-night fun 💗":"New premium drop just landed."}</p><Link className={styles.primary} href="/fanxfantasy/unlock">Unlock ${n===1?"8.99":"12.99"}</Link></div></article>)}</div><aside className={styles.card}><span className={styles.kicker}>Trending</span><h3>Creators to watch</h3>{creators.slice(0,3).map(([n,h])=><div className={styles.listItem} key={n}><strong>{n}</strong><span className={styles.muted}>{h}</span></div>)}</aside></div>}
function Unlock(){return <div className={styles.checkout}><section><div className={styles.post}><div className={`${styles.postMedia} ${styles.locked}`}/><div className={styles.postFoot}><span className={styles.kicker}>Premium content</span><h1>Steamy shower set</h1><p className={styles.muted}>A private premium creator set from Scarlett May.</p></div></div></section><aside className={styles.summary}><h2>Unlock content</h2><div className={styles.row}><span>Single unlock</span><b>$12.99</b></div><div className={styles.row}><span>Premium members</span><b>20% off</b></div><Link className={styles.primary} href="/fanxfantasy/checkout">Unlock now</Link><p className={styles.muted}>18+ confirmation required at checkout.</p></aside></div>}
function Tiers(){return <><div className={styles.sectionHead}><div><span className={styles.kicker}>Choose your experience</span><h2>Subscription tiers</h2></div></div><div className={styles.tiers}>{[["Follower","Free","Public posts & updates"],["Fan","$9.99/mo","Standard premium content"],["Premium","$19.99/mo","Full creator library + early access"],["VIP","$49.99/mo","Exclusive drops + private requests"]].map(([n,p,d],i)=><article className={`${styles.tier} ${i===2?styles.featured:""}`} key={n}><h3>{n}</h3><strong>{p}</strong><p className={styles.muted}>{d}</p><ul><li>Creator feed access</li><li>Member-only drops</li><li>Saved library access</li>{i>1&&<li>Priority messaging</li>}</ul><Link className={styles.primary} href="/fanxfantasy/checkout">Subscribe</Link></article>)}</div></>}
function Messages(){return <div className={styles.messages}><aside className={styles.inbox}>{creators.map(([n,h],i)=><div className={styles.listItem} key={n}><strong>{n}</strong><span className={styles.muted}>{i===0?"Last message: Can’t wait 💗":h}</span></div>)}</aside><section className={styles.chat}><div className={styles.chatHeader}><b>Scarlett May ✓</b><span className={styles.muted}> · online</span></div><div className={styles.thread}><div className={styles.bubble}>Hey babe 💗 thanks for being here.</div><div className={`${styles.bubble} ${styles.mine}`}>Love your new set!</div><div className={styles.bubble}>I saved something special in the vault for you ✨</div><div className={`${styles.card} ${styles.locked}`} style={{height:180,maxWidth:320}}></div></div><div className={styles.chatInput}>Type a message…</div></section></div>}
function Marketplace(){return <><div className={styles.sectionHead}><div><span className={styles.kicker}>Marketplace</span><h2>Bundles, images, videos & prompts</h2></div></div><div className={styles.tabs}>{["All","Bundles","Images","Videos","Prompts"].map((x,i)=><span key={x} className={`${styles.tab} ${i===0?styles.tabActive:""}`}>{x}</span>)}</div><div className={styles.grid3}>{["Scarlett Collection","Beach Babe Set","Sunset Dreams","VIP Video Pack","Creator Prompt Vault","AI Girlfriend Fantasy Kit"].map((n,i)=><Link href="/fanxfantasy/checkout" className={styles.product} key={n}><div className={styles.productMedia}/><div className={styles.productCopy}><b>{n}</b><p className={styles.muted}>{i%2?"Premium video + image bundle":"Exclusive creator product"}</p><span className={styles.price}>${[24.99,19.99,16.99,39.99,9.99,27][i]}</span></div></Link>)}</div></>}
function Checkout(){return <div className={styles.checkout}><section className={styles.card}><span className={styles.kicker}>Secure checkout</span><h1>Complete your order</h1><div className={styles.field}>Email address</div><div className={styles.field}>Card details / Stripe Checkout</div><div className={styles.ageNote}><b>18+</b><span>I confirm I am 18 years or older.</span></div></section><aside className={styles.summary}><h3>Order summary</h3><div className={styles.row}><span>Scarlett Collection</span><b>$24.99</b></div><div className={styles.row}><span>Premium subscription</span><b>$19.99</b></div><div className={styles.row}><span>Discount</span><b>-$9.00</b></div><div className={styles.row}><strong>Total AUD</strong><strong className={styles.price}>$35.98</strong></div><Link className={styles.primary} href="/fanxfantasy/success">Pay $35.98 AUD</Link></aside></div>}
function Success(){return <section className={styles.success}><div className={styles.successMark}>✓</div><span className={styles.kicker}>Payment successful</span><h1>Your fantasy is unlocked.</h1><p className={styles.muted}>Your purchase is now available inside My Library.</p><div className={styles.row}><span>Scarlett Collection</span><b>Unlocked</b></div><div className={styles.row}><span>Premium subscription</span><b>Active</b></div><Link className={styles.primary} href="/fanxfantasy/library">Go to My Library</Link></section>}
function Library(){return <><div className={styles.sectionHead}><div><span className={styles.kicker}>My library</span><h2>Your unlocked content</h2></div></div><div className={styles.tabs}>{["All","Images","Videos","Bundles","Downloads"].map((x,i)=><span key={x} className={`${styles.tab} ${i===0?styles.tabActive:""}`}>{x}</span>)}</div><div className={styles.grid3}>{[1,2,3,4,5,6].map(n=><div className={styles.card} key={n}><div className={styles.media}/><div className={styles.creatorMeta}><b>{n%2?"Scarlett Collection":"Saved premium post"}</b><span className={styles.tag}>Owned</span></div></div>)}</div></>}
function Dashboard(){return <><div className={styles.sectionHead}><div><span className={styles.kicker}>Creator dashboard</span><h2>Scarlett May</h2></div><Link className={styles.primary} href="/fanxfantasy/create">Create post</Link></div><div className={styles.metricGrid}>{[["Revenue","$12,876"],["Subscribers","1,248"],["Content sales","$3,420"],["Conversion","6.3%"]].map(([a,b])=><div className={styles.metric} key={a}><span className={styles.muted}>{a}</span><br/><strong>{b}</strong></div>)}</div><div className={styles.dashboardLayout} style={{marginTop:16}}><div><div className={styles.chart}/></div><aside className={styles.card}><h3>Recent activity</h3><div className={styles.listItem}><strong>New subscription</strong><span className={styles.price}>+$19.99</span></div><div className={styles.listItem}><strong>Content sold</strong><span className={styles.price}>+$12.99</span></div><div className={styles.listItem}><strong>Unread messages</strong><span className={styles.price}>23</span></div></aside></div></>}
function CharacterStudio(){return <><div className={styles.sectionHead}><div><span className={styles.kicker}>AI Character Studio</span><h2>Build & lock character identity</h2></div></div><div className={styles.studio}><aside className={styles.studioPanel}><div className={styles.portrait}/><div className={styles.field}>Name: Scarlett May</div><div className={styles.field}>Age: 25+</div><div className={styles.field}>Persona: confident, playful, premium</div></aside><section className={styles.studioPanel}><h3>Character profile</h3><div className={styles.field}>Appearance consistency: High</div><div className={styles.field}>Voice & style: Flirty, warm, premium creator tone</div><div className={styles.field}>Outfits: Luxury, activewear, nightlife, editorial</div><div className={styles.field}>Locations: Penthouse, neon studio, beach, city night</div><div className={styles.field}>Reference images: 5 locked</div><div className={styles.field}>Face consistency target: 85%</div><button className={styles.primary} style={{marginTop:14}}>Save character</button></section><aside className={styles.studioPanel}><h3>Automation</h3><div className={styles.row}><span>Auto captions</span><b>ON</b></div><div className={styles.row}><span>Chat persona</span><b>ON</b></div><div className={styles.row}><span>Upsell logic</span><b>ON</b></div><Link className={styles.primary} href="/fanxfantasy/create">Create content</Link></aside></div></>}
function Create(){return <><div className={styles.sectionHead}><div><span className={styles.kicker}>Content Creation Studio</span><h2>Create, price & publish</h2></div></div><div className={styles.studio}><aside className={styles.studioPanel}><h3>1. Character</h3><div className={styles.portrait}/><div className={styles.field}>Scarlett May</div></aside><section className={styles.studioPanel}><div className={styles.tabs}><span className={`${styles.tab} ${styles.tabActive}`}>Image</span><span className={styles.tab}>Video</span><span className={styles.tab}>Story</span></div><div className={styles.field}>Prompt: luxury penthouse, confident pose, cinematic pink rim light, 85mm portrait…</div><div className={styles.field}>Style: Photorealistic</div><div className={styles.field}>Lighting: Neon editorial</div><div className={styles.media} style={{marginTop:12}}/><button className={styles.primary} style={{marginTop:14}}>Generate AI</button></section><aside className={styles.studioPanel}><h3>4. Publish</h3><div className={styles.field}>Access: Premium</div><div className={styles.field}>Price: $9.99 AUD</div><div className={styles.field}>Schedule: Tonight 6:00 PM</div><div className={styles.ageNote}><b>18+</b><span>Adult publishing requires compliant provider output and age gating.</span></div><button className={styles.primary} style={{marginTop:14}}>Schedule post</button></aside></div></>}
function Analytics(){return <><div className={styles.sectionHead}><div><span className={styles.kicker}>Analytics · earnings · settings</span><h2>Performance overview</h2></div></div><div className={styles.metricGrid}>{[["Revenue","$12,450"],["Subscribers","1,248"],["Views","78.4K"],["Sales","342"]].map(([a,b])=><div className={styles.metric} key={a}><span className={styles.muted}>{a}</span><br/><strong>{b}</strong><div className={styles.price}>+21%</div></div>)}</div><div className={styles.grid2} style={{marginTop:16}}><div className={styles.chart}/><div className={styles.card}><h3>Top content</h3><div className={styles.row}><span>Steamy shower set</span><b>$1,234</b></div><div className={styles.row}><span>Beach Babe Set</span><b>$982</b></div><div className={styles.row}><span>Sunset photoset</span><b>$876</b></div><div className={styles.row}><span>Message revenue</span><b>$1,234</b></div></div></div>}

export default function FanXFantasyApp({view}:{view:View}){let body:React.ReactNode;switch(view){case"explore":body=<Explore/>;break;case"profile":body=<Profile/>;break;case"feed":body=<Feed/>;break;case"unlock":body=<Unlock/>;break;case"tiers":body=<Tiers/>;break;case"messages":body=<Messages/>;break;case"marketplace":body=<Marketplace/>;break;case"checkout":body=<Checkout/>;break;case"success":body=<Success/>;break;case"library":body=<Library/>;break;case"dashboard":body=<Dashboard/>;break;case"character-studio":body=<CharacterStudio/>;break;case"create":body=<Create/>;break;case"analytics":body=<Analytics/>;break;default:body=<Home/>}return <Shell view={view}>{body}</Shell>}
