import Link from "next/link";

export const dynamic = "force-dynamic";

export default async function AgeCheckPage({searchParams}:{searchParams:Promise<{returnTo?:string;error?:string}>}){
  const p=await searchParams;
  const configured=Boolean(process.env.AGE_ASSURANCE_PROVIDER_URL && process.env.AGE_ASSURANCE_PROVIDER_KEY && process.env.AGE_GATE_SECRET);
  const returnTo=(p.returnTo||"/fanxfantasy").startsWith("/")?p.returnTo:"/fanxfantasy";
  return <main style={{minHeight:"100vh",background:"#070708",color:"#fff",display:"grid",placeItems:"center",padding:24,fontFamily:"Inter,system-ui,sans-serif"}}><section style={{width:"min(620px,100%)",border:"1px solid #2c2c33",borderRadius:24,background:"#111115",padding:"clamp(24px,6vw,42px)"}}><div style={{color:"#ff2d8d",fontWeight:900,letterSpacing:".14em",textTransform:"uppercase",fontSize:12}}>FanXFantasy · Australia</div><h1 style={{fontSize:"clamp(2rem,7vw,3.4rem)",margin:"10px 0"}}>Age assurance required</h1><p style={{color:"#b7b7c0",lineHeight:1.7}}>Australian users must complete an appropriate age-assurance check before accessing pornography, sexually explicit AI generation or adult-specialised messaging. A simple “I am 18+” button is not used as verification.</p>{p.error?<div style={{border:"1px solid #6b273f",background:"#241017",padding:14,borderRadius:14,color:"#ff9abb"}}>{p.error}</div>:null}<div style={{margin:"22px 0",padding:16,borderRadius:16,background:"#0b0b0e",border:"1px solid #292930"}}><strong>Privacy-first design</strong><p style={{color:"#9999a6",lineHeight:1.6,marginBottom:0}}>CQA only stores a signed “age verified” result, not identity documents or facial images. The age-assurance provider must handle verification data under its own privacy controls.</p></div>{configured?<form action="/api/age/start" method="post"><input type="hidden" name="returnTo" value={returnTo}/><button style={{width:"100%",border:0,borderRadius:999,padding:"14px 18px",background:"#ff2d8d",color:"#fff",fontWeight:900,cursor:"pointer"}}>Verify age securely</button></form>:<div style={{padding:16,borderRadius:16,border:"1px solid #705022",background:"#21180d",color:"#ffd291"}}><b>Age-assurance provider not connected yet.</b><br/>Adult content remains locked until a compliant provider is configured.</div>}<div style={{display:"flex",gap:16,marginTop:20,flexWrap:"wrap"}}><Link href="/fanxfantasy" style={{color:"#ff6aa9"}}>Return to safe preview</Link><Link href="/compliance" style={{color:"#a9a9b5"}}>Safety & compliance</Link></div></section></main>
}
