"use client";

import { Suspense,useEffect,useState } from "react";
import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { createClient } from "@supabase/supabase-js";

type Status={complete:boolean;paymentStatus:string;checkoutStatus:string;order:{id:string;kind:string;status:string;gross_cents:number;currency:string;metadata:Record<string,unknown>}};
function Success(){const params=useSearchParams();const sessionId=params.get("session_id")||"";const [status,setStatus]=useState<Status|null>(null);const [error,setError]=useState("");
 useEffect(()=>{let stopped=false;async function check(attempt=0){const u=process.env.NEXT_PUBLIC_SUPABASE_URL||"";const k=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY||"";if(!u||!k){setError("Account service is unavailable.");return}const sb=createClient(u,k);const {data}=await sb.auth.getSession();const token=data.session?.access_token;if(!token){window.location.assign(`/fanxfantasy/auth?next=${encodeURIComponent(`/fanxfantasy/success?session_id=${sessionId}`)}`);return}const r=await fetch(`/api/fanx/checkout-status?session_id=${encodeURIComponent(sessionId)}`,{headers:{Authorization:`Bearer ${token}`},cache:"no-store"});const p=await r.json().catch(()=>({}));if(!r.ok){setError(p.error||"Could not verify payment.");return}if(stopped)return;setStatus(p);if(!p.complete&&p.paymentStatus==="paid"&&attempt<8)setTimeout(()=>check(attempt+1),1200)}if(sessionId)check();else setError("No checkout session was supplied.");return()=>{stopped=true}},[sessionId]);
 return <main style={main}><section style={box}>{error?<><div style={bad}>!</div><h1>We couldn’t verify this payment.</h1><p style={muted}>{error}</p><Link href="/fanxfantasy/marketplace" style={secondary}>Return to marketplace</Link></>:status?.complete?<><div style={ok}>✓</div><span style={kicker}>Payment verified</span><h1>Your purchase is unlocked.</h1><p style={muted}>Order {status.order.id.slice(0,8)} · ${(status.order.gross_cents/100).toFixed(2)} {status.order.currency.toUpperCase()}</p><p style={muted}>The Stripe webhook has recorded the transaction and generated your entitlement.</p><Link href="/fanxfantasy/library" style={primary}>Open My Library</Link></>:<><div style={wait}>…</div><span style={kicker}>Payment received</span><h1>Finishing your unlock.</h1><p style={muted}>Stripe reports the checkout as {status?.paymentStatus||"processing"}. We’re waiting for the signed webhook before granting access.</p><p style={muted}>Do not pay again. This page will check automatically.</p><Link href="/fanxfantasy/library" style={secondary}>Check My Library</Link></>}</section></main>}
export default function SuccessPage(){return <Suspense><Success/></Suspense>}
const main:React.CSSProperties={minHeight:"100vh",background:"#070708",color:"white",display:"grid",placeItems:"center",padding:24,fontFamily:"Inter,system-ui,sans-serif"};const box:React.CSSProperties={width:"min(650px,100%)",border:"1px solid #2c2c33",background:"#111115",borderRadius:24,padding:"clamp(28px,6vw,48px)",textAlign:"center"};const muted:React.CSSProperties={color:"#aaaab5",lineHeight:1.65};const kicker:React.CSSProperties={color:"#ff2d8d",fontWeight:900,textTransform:"uppercase",letterSpacing:".13em",fontSize:12};const icon:React.CSSProperties={width:72,height:72,borderRadius:"50%",display:"grid",placeItems:"center",margin:"0 auto 18px",fontSize:30,fontWeight:900};const ok={...icon,background:"#1b5036",color:"#a8f0cb"};const bad={...icon,background:"#542035",color:"#ffaccb"};const wait={...icon,background:"#3b2c12",color:"#ffd68b"};const primary:React.CSSProperties={display:"inline-block",background:"#ff2d8d",color:"white",padding:"13px 19px",borderRadius:999,fontWeight:900,textDecoration:"none",marginTop:14};const secondary:React.CSSProperties={...primary,background:"transparent",border:"1px solid #45454f"};
