import Link from "next/link";
import FanXCheckoutButton from "@/components/FanXCheckoutButton";
import { getFanXDb } from "@/lib/fanx-db";

export const dynamic="force-dynamic";

export default async function MarketplacePage(){
 const db=getFanXDb();
 const {data:products}=await db.from("fanx_products").select("id,slug,title,description,cover_url,product_type,price_cents,creator_id,fanx_creators(slug,display_name)").eq("active",true).order("created_at",{ascending:false});
 return <main style={main}><Header/><section style={wrap}><span style={kicker}>FanX marketplace</span><h1 style={h1}>Premium drops & creator products</h1><p style={muted}>Products here are live database records. Purchases create a Stripe order and unlock a permanent library entitlement only after the verified webhook completes.</p><div style={grid}>{(products||[]).map((p)=>{const creator=Array.isArray(p.fanx_creators)?p.fanx_creators[0]:p.fanx_creators;return <article key={p.id} style={card}><div style={{height:250,borderRadius:16,background:`linear-gradient(rgba(0,0,0,.12),rgba(0,0,0,.4)),url(${p.cover_url||"/fanx/mascot.png"}) center/cover`}}/><div style={{paddingTop:15}}><span style={kicker}>{p.product_type.replaceAll("_"," ")}</span><h2 style={{margin:"7px 0"}}>{p.title}</h2><p style={muted}>{p.description}</p><div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"center",flexWrap:"wrap"}}><strong style={{fontSize:22,color:"#ff5aa2"}}>${(p.price_cents/100).toFixed(2)} AUD</strong><FanXCheckoutButton kind="product" creatorSlug={creator?.slug||"scarlett-may"} itemKey={p.slug}>Buy now</FanXCheckoutButton></div></div></article>})}</div></section></main>
}
function Header(){return <header style={header}><Link href="/fanxfantasy"><img src="/fanx/logo.png" alt="FanXFantasy" style={{height:54,width:170,objectFit:"contain"}}/></Link><nav><Link href="/fanxfantasy/explore" style={nav}>Creators</Link><Link href="/fanxfantasy/library" style={nav}>Library</Link><Link href="/fanxfantasy/auth" style={nav}>Account</Link></nav></header>}
const main:React.CSSProperties={minHeight:"100vh",background:"#070708",color:"white",fontFamily:"Inter,system-ui,sans-serif"};const header:React.CSSProperties={display:"flex",justifyContent:"space-between",alignItems:"center",padding:"12px clamp(16px,4vw,54px)",borderBottom:"1px solid #25252b"};const wrap:React.CSSProperties={width:"min(1180px,92vw)",margin:"0 auto",padding:"56px 0 100px"};const grid:React.CSSProperties={display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(270px,1fr))",gap:18,marginTop:28};const card:React.CSSProperties={border:"1px solid #2a2a31",borderRadius:20,padding:14,background:"#111115"};const kicker:React.CSSProperties={color:"#ff2d8d",fontSize:12,fontWeight:900,textTransform:"uppercase",letterSpacing:".13em"};const h1:React.CSSProperties={fontSize:"clamp(2.2rem,6vw,4.4rem)",margin:"8px 0"};const muted:React.CSSProperties={color:"#aaaab5",lineHeight:1.6};const nav:React.CSSProperties={color:"#ccc",marginLeft:16};
