-- CQA Digital Vending Machine System schema
create extension if not exists "pgcrypto";

create table if not exists public.profiles (
  id uuid primary key,
  email text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric(10,2) not null,
  stripe_price_id text not null unique
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  product_id bigint not null references public.products(id),
  stripe_session_id text not null unique,
  status text not null default 'paid',
  created_at timestamptz not null default now()
);

create table if not exists public.downloads (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  product_id bigint not null references public.products(id),
  download_token text not null unique,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.downloads enable row level security;

create policy "profiles_self_select" on public.profiles
for select using (auth.uid() = id);

create policy "orders_self_select" on public.orders
for select using (auth.uid() = user_id);

create policy "downloads_self_select" on public.downloads
for select using (auth.uid() = user_id);

create policy "products_authenticated_select" on public.products
for select to authenticated using (true);
