import { NextResponse } from "next/server";
import { AGE_COOKIE,verifyAgeToken } from "@/lib/age-assurance";
import { requireFanXUser,bearerError } from "@/lib/fanx-auth";
import { getFanXDb } from "@/lib/fanx-db";

function cv(r:Request,n:string){const raw=r.headers.get("cookie")||"";for(const p of raw.split(";")){const [k,...v]=p.trim().split("=");if(k===n)return decodeURIComponent(v.join("="))}return null}
function slugify(v:string){return v.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,42)||"creator"}
export async function GET(request:Request){try{const u=await requireFanXUser(request);const db=getFanXDb();const {data}=await db.from("fanx_creators").select("id,slug,display_name,handle,bio,avatar_url,cover_url,verified,status,stripe_account_id,payout_mode").eq("owner_user_id",u.id).maybeSingle();return NextResponse.json({creator:data})}catch(e){const x=bearerError(e);return NextResponse.json({error:x.message},{status:x.status})}}
export async function POST(request:Request){try{if(!verifyAgeToken(cv(request,AGE_COOKIE)))return NextResponse.json({error:"Verified age assurance is required for creators."},{status:403});const u=await requireFanXUser(request);const body=await request.json().catch(()=>({})) as {displayName?:string;handle?:string;bio?:string};const displayName=String(body.displayName||"").trim().slice(0,80);if(displayName.length<2)return NextResponse.json({error:"Creator name is required."},{status:400});const db=getFanXDb();const {data:existing}=await db.from("fanx_creators").select("id,slug,display_name,handle").eq("owner_user_id",u.id).maybeSingle();if(existing)return NextResponse.json({creator:existing,existing:true});const base=slugify(String(body.handle||displayName));const slug=`${base}-${u.id.slice(0,6)}`;const handle=`@${base.replace(/-/g,"").slice(0,24)}${u.id.slice(0,3)}`;const {data,error}=await db.from("fanx_creators").insert({owner_user_id:u.id,slug,display_name:displayName,handle,bio:String(body.bio||"").slice(0,500),verified:false,status:"active",payout_mode:"platform_owned"}).select("id,slug,display_name,handle,status").single();if(error)throw new Error(error.message);await db.from("fanx_profiles").upsert({user_id:u.id,role:"creator",display_name:displayName},{onConflict:"user_id"});return NextResponse.json({creator:data})}catch(e){const x=bearerError(e);return NextResponse.json({error:x.message},{status:x.status})}}
